#Mind Reader

##Introduction
The Mind Reader is an application capable of knowing the number on your mind based on how you answer the questions provided by it.

##Programming Environment
Eclipse. If you're using Eclipse, you can simply import the whole project.

##Directories
###src
Contains the source code.

###bin
Contains the compiled Java classes.

###doc
Contains the documents for describing the classes, methods, and instance variables. This has been automatically generated by JavaDoc.

###jar
Contains the Java Archive (.jar) executable file for the application.

##Notes
Make sure to update the .jar file in the jar directory if you change the source code so that it will reflect the changes.

##Online Version
You can view an online version of the application which I created using PHP:
http://assim.me/projects/mindreader/

##License
Mind Reader by Assim Al-Marhuby (assim1991@gmail.com) is licensed under a Creative Commons Attribution-NonCommercial 3.0 Unported License.

The copy of the license can be found at:

http://creativecommons.org/licenses/by-nc/3.0/